[package]
name = "UntitledSexualityProject"
description = ""
license = "MIT"
repository = "git@github.com:CultOfTheBlob/UntitledSexualityProject.git"
keywords = []
categories = []
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.36.0"
eframe = { version = "0.36.0", features = ["persistence"] }
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
printpdf = { version = "0.12.8", features = ["html", "png", "jpeg", "webp"] }
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.70", features = ["Window", "Document", "Element", "HtmlAnchorElement", "Url", "Blob", "BlobPropertyBag"] } 
js-sys = "0.3.105"
rfd = "0.17.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

dbg_macro = "warn"

unwrap_used = "warn"
expect_used = "warn"
exit = "warn"
mem_forget = "warn"
create_dir = "warn"
assertions_on_result_states = "warn"
tests_outside_test_module = "warn"

missing_errors_doc = "warn"
missing_safety_doc = "warn"
missing_panics_doc = "warn"

large_types_passed_by_value = "warn"
unnecessary_box_returns = "warn"

cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
cast_possible_wrap = "allow"
float_cmp_const = "allow"

print_stdout = "allow"
print_stderr = "allow"

missing_const_for_fn = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
struct_excessive_bools = "allow"
too_many_lines = "allow"
fn_params_excessive_bools = "allow"

cargo_common_metadata = "allow"
multiple_crate_versions = "allow"

wildcard_imports = "allow"
let_underscore_must_use = "allow"
significant_drop_tightening = "allow"

[lints.rust]
irrefutable_let_patterns = "allow"
non_snake_case = "allow"
