import {
    RadioGroup,
    ComboBox,
    LineEdit,
    Palette,
    Button,
    ScrollView,
} from "std-widgets.slint";

export struct SpectrumData {
    name: string,
    data: string,
}

component SpectrumInput inherits Rectangle {
    in property <string> name;

    pure callback validate-input(string) -> bool;

    out property <string> selected-mode: combo.current-value;
    out property <bool> num-valid: selected-mode == "Number" ? root.validate-input(input.text) : true;
    out property <SpectrumData> data: {
        name: root.name,
        data: selected-mode == "Number" ? input.text : selected-mode == "Quadrants" ? quadrants.current-value : combo.current-value,
    };

    width: 256px;
    height: 64px;

    HorizontalLayout {
        alignment: start;
        cross-axis-alignment: center;
        spacing: 16px;

        Text {
            text: root.name;
        }

        combo := ComboBox {
            model: ["Quadrants", "Unknown", "Number"];
            current-value: "Quadrants";
        }

        Rectangle {
            property <bool> is-enabled: combo.current-value == "Quadrants";

            width: is-enabled ? quadrants-layout.preferred-width : 0px;
            opacity: is-enabled ? 1 : 0;

            visible: self.width > 0px || is-enabled;
            clip: true;

            animate width {
                duration: 250ms;
                easing: ease-out;
            }
            animate opacity {
                duration: 200ms;
                easing: ease-in-out;
            }

            quadrants-layout := HorizontalLayout {
                alignment: start;
                cross-axis-alignment: center;
                spacing: 8px;

                quadrants := RadioGroup {
                    orientation: horizontal;

                    RadioButton {
                        text: "Q1";
                    }

                    RadioButton {
                        text: "Q2";
                    }

                    RadioButton {
                        text: "M";
                        checked: true;
                    }

                    RadioButton {
                        text: "Q3";
                    }

                    RadioButton {
                        text: "Q4";
                    }
                }

                Rectangle {
                    width: 4px;
                }

                Image {
                    source: @image-url("../assets/icons/info.svg");
                    width: 20px;
                    height: 20px;
                    colorize: Palette.foreground;

                    Tooltip {
                        text: @markdown(
                            "Q1 through Q4 represent 4 evenly spaced quadrants of the spectrum"
                            "\n"
                            "M represents the middle of the spectrum"
                        );
                    }
                }
            }
        }

        Rectangle {
            property <bool> is-enabled: combo.current-value == "Number";

            width: is-enabled ? number-layout.preferred-width : 0px;
            opacity: is-enabled ? 1.0 : 0.0;

            visible: self.width > 0px || is-enabled;
            clip: true;

            animate width {
                duration: 250ms;
                easing: ease-out;
            }
            animate opacity {
                duration: 200ms;
                easing: ease-in-out;
            }

            number-layout := HorizontalLayout {
                alignment: start;
                cross-axis-alignment: center;
                spacing: 8px;

                VerticalLayout {
                    padding: 2px;

                    input := LineEdit {
                        text: "0.0";
                        placeholder-text: "0.0 to 1.0";
                    }
                }

                Rectangle {
                    width: 4px;
                }

                Image {
                    source: @image-url("../assets/icons/info.svg");
                    width: 20px;
                    height: 20px;
                    colorize: Palette.foreground;

                    Tooltip {
                        text: @markdown(
                            "any number or range between \u{2205} and 1.0 is valid"
                            "\n"
                            "a range can be represented as <font color='\{Colors.yellow}'>\"_[from~to]_\"</font> "
                            "where _from_ and _to_ are valid numbers inside between \u{2205} and 1.0"
                            "and _from_ is smaller than _to_"
                            "\n"
                            "use 0 or 0.0 to represent \u{2205}"
                        );
                    }
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    pure callback validate-input(string) -> bool;

    callback submit-spectrums([SpectrumData]);

    property <[string]> spectrums: [
        "Spectrum 0",
        "Spectrum 1",
        "Spectrum 2",
        "Spectrum 3",
        "Spectrum 4",
        "Spectrum 5",
        "Spectrum 6",
        "Spectrum 7",
        "Spectrum 8",
        "Spectrum 9",
    ];

    property <[SpectrumData]> spectrum-data-list: [
        { name: "Spectrum 0", data: "Quadrants" },
        { name: "Spectrum 1", data: "Quadrants" },
        { name: "Spectrum 2", data: "Quadrants" },
        { name: "Spectrum 3", data: "Quadrants" },
        { name: "Spectrum 4", data: "Quadrants" },
        { name: "Spectrum 5", data: "Quadrants" },
        { name: "Spectrum 6", data: "Quadrants" },
        { name: "Spectrum 7", data: "Quadrants" },
        { name: "Spectrum 8", data: "Quadrants" },
        { name: "Spectrum 9", data: "Quadrants" },
    ];

    property <int> invalid-count: 0;
    property <bool> is-all-valid: invalid-count == 0;

    ScrollView {
        width: 100%;
        height: 100%;

        VerticalLayout {
            VerticalLayout {
                alignment: start;
                padding: 24px;
                spacing: 24px;

                for spectrum[index] in root.spectrums: VerticalLayout {
                    spacing: 24px;

                    input-item := SpectrumInput {
                        name: spectrum;

                        validate-input(s) => { root.validate-input(s) }

                        changed data => {
                            root.spectrum-data-list[index] = self.data;
                        }

                        changed num-valid => {
                            if (self.num-valid) {
                                root.invalid-count -= 1;
                            } else {
                                root.invalid-count += 1;
                            }
                        }
                    }

                    if index < root.spectrums.length - 1: Rectangle {
                        property <brush> bg: Palette.background;
                        property <brush> alt-bg: Palette.alternate-background;

                        width: 100%;
                        height: 2px;
                        background: @linear-gradient(90deg, bg 0%, alt-bg 50%, bg 100%);
                    }
                }
            }

            Rectangle { }

            HorizontalLayout {
                alignment: end;
                padding-right: 16px;
                padding-bottom: 16px;

                Button {
                    text: "Confirm";
                    primary: true;
                    enabled: root.is-all-valid;

                    clicked => {
                        root.submit-spectrums(root.spectrum-data-list);
                    }
                }
            }
        }
    }
}
